Repository cellml/cellml-specification, pull requests merged in 2020-04, with the labels that each got.

#151 i138 Informative 3.4 References to component elements
  src/reference/formal_and_informative/specC04_component_reference.rst
  src/reference/informative/informC04_component_reference.rst
Labels: informative

#148 i137 Informative 3.2 units reference
  src/reference/formal_and_informative/specC02_units_reference.rst
  src/reference/informative/informC02_units_reference.rst
Labels: informative

#193 i55 Writing informative section for 1.2.6
  src/reference/formal_and_informative/specA2.rst
  src/reference/informative/informA2_4.rst
  src/reference/informative/informA2_6.rst
Labels: informative

#174 i143 3.10 map_variables informative
  src/conf.py
  src/reference/formal_and_informative/specC10_interpretation_of_map_variables.rst
  src/reference/informative/informC10_interpretation_of_map_variables.rst
  src/reference/informative/informC10_interpretation_of_map_variables1.rst
  src/reference/informative/informC10_interpretation_of_map_variables2.rst
  src/reference/informative/informC10_interpretation_of_map_variables3.rst
  src/reference/informative/informC10_interpretation_of_map_variables4.rst
  src/reference/informative/informC10_interpretation_of_map_variables5.rst
  src/reference/informative/informC10_interpretation_of_map_variables6.rst
  src/reference/sectionC_interpretation.inc
Labels: informative

#168 i142 3.9 Interpretation of encapsulations, informative
  src/reference/formal_and_informative/specC09_interpretation_of_encapsulation.rst
  src/reference/informative/informC09_interpretation_of_encapsulation.rst
  src/reference/informative/informC09_interpretation_of_encapsulation1.rst
  src/reference/informative/informC09_interpretation_of_encapsulation2.rst
  src/reference/informative/informC09_interpretation_of_encapsulation3.rst
  src/reference/sectionC_interpretation.inc
Labels: informative

#152 i139 Informative 3.5 variable references
  src/reference/formal_and_informative/specC05_variable_reference.rst
  src/reference/informative/informC05_variable_reference.rst
Labels: informative

#186 Formatting issue in 2.12.4 mathml:math element
  src/reference/sectionB_elements.inc
Labels: normative

#175 Rewording points in 3.10
  src/reference/sectionC_interpretation.inc
Labels: normative

#200 Identifier rules
  src/reference/sectionA_definitions.inc
Labels: normative

#199 Changes to number string definitions
  src/reference/formal_and_informative/specA3.rst
  src/reference/informative/informA1.rst
  src/reference/informative/informA3_2.rst
  src/reference/informative/informA3_3.rst
  src/reference/informative/informA3_4.rst
  src/reference/informative/informA3_5.rst
  src/reference/sectionA_definitions.inc
Labels: informative, normative

#203 Added must-be-identifier for reset variables
  src/reference/sectionB_elements.inc
Labels: normative

#202 Non-specific item section
  src/reference/formal_and_informative/specA2.rst
  src/reference/informative/informA2_3_2.rst
  src/reference/informative/informA2_3_3.rst
  src/reference/informative/informA2_5.rst
  src/reference/sectionA_definitions.inc
Labels: normative

#210 i176 Change connected/mapped variables into equivalent variables
  src/reference/informative/informB15_connection3.rst
  src/reference/informative/informB8_variable1.rst
  src/reference/sectionB_elements.inc
  src/reference/sectionC_interpretation.inc
Labels: normative

#209 Changes to 2.8 and 3.7 as per discussion
  src/reference/sectionB_elements.inc
  src/reference/sectionC_interpretation.inc
Labels: normative

#215 Slight change to reset wording.
  src/reference/sectionC_interpretation.inc
Labels: normative

#216 Tiny change to equivalence definition.
  src/reference/sectionA_definitions.inc
Labels: normative

#227 Tweaks to preamble of norm spec.
  src/normative_only_index.rst
Labels: normative

#217 Changed character classes to consistently be numericAL or alphabeticAL
  src/reference/informative/informA1.rst
  src/reference/sectionA_definitions.inc
Labels: normative

#218 CellML Namespace is now consistently a link.
  src/reference/sectionB_elements.inc
Labels: normative

#220 Tiny list punctuation fixes.
  src/reference/sectionA_definitions.inc
  src/reference/sectionB_elements.inc
Labels: normative

#222 Updates to terminology section wording as suggested in #197.
  src/reference/sectionA_definitions.inc
Labels: normative

#224 Consistent "which appears as a child of" wording for all elements
  src/reference/sectionB_elements.inc
Labels: normative

#223 Change to whitespace-in-elements wording
  src/reference/sectionA_definitions.inc
Labels: normative

#225 Chapter 2: Lists of children are alphabetical.
  src/reference/sectionB_elements.inc
Labels: normative

#228 Removed ununsed columns from predefined units table.
  src/reference/sectionC_interpretation.inc
Labels: normative

#236 I197 element information items -> elements
  src/reference/sectionC_interpretation.inc
Labels: normative

#241 Resolve any or none
  src/reference/sectionA_definitions.inc
Labels: normative

#244 i243 remove hash from rfc link
  src/conf.py
  src/reference/sectionD_references.inc
Labels: normative

#212 Reworded import interpretation.
  src/reference/sectionC_interpretation.inc
Labels: normative

#230 Updates to unit, component, and variable reference interpretation
  src/reference/sectionB_elements.inc
  src/reference/sectionC_interpretation.inc
Labels: normative

#248 Consistently using 'identical' when comparing identifiers.
  src/reference/sectionB_elements.inc
  src/reference/sectionC_interpretation.inc
Labels: normative

#266 I245 internal hyperlinks
  src/reference/sectionA_definitions.inc
  src/reference/sectionB_elements.inc
  src/reference/sectionC_interpretation.inc
Labels: normative

#274 Spelling
  src/reference/informative_preamble.inc
Labels: informative

#267 Various small fixes
  src/reference/sectionB_elements.inc
  src/reference/sectionC_interpretation.inc
Labels: normative

#270 Stopped cross-references in PDF from showing up in italics.
  src/conf.py
Labels: normative

#269 Changed 'see X' links from `:ref:` to `:numref:`
  src/reference/sectionB_elements.inc
  src/reference/sectionC_interpretation.inc
Labels: normative

#284 Made normative-only the default build.
  README.rst
  src/conf.py
Labels: web-and-infra

#268 Encapsulation loops
  src/reference/sectionB_elements.inc
  src/reference/sectionC_interpretation.inc
Labels: normative

#285 Using the power of numref.
  src/conf.py
  src/reference/informative/informC09_interpretation_of_encapsulation2.rst
  src/reference/informative/informC09_interpretation_of_encapsulation3.rst
  src/reference/informative/informC10_interpretation_of_map_variables3.rst
  src/reference/sectionB_elements.inc
  src/reference/sectionC_interpretation.inc
Labels: normative

#295 Added latex info to README.rst.
  README.rst
Labels: web-and-infra

#287 I280 numbering references
  src/conf.py
  src/reference/sectionA_definitions.inc
  src/reference/sectionB_elements.inc
  src/reference/sectionD_references.inc
Labels: normative

#166 Single page generation suitable for cellml.org
  src/conf.py
  src/static/images/unofficial_version_dark_background.png
  src/static/images/unofficial_version_dark_background_green.png
  src/static/templates/layout.html
  src/static/templates/page.html
Labels: normative

#297 Final tweaks
  src/conf.py
  src/normative_only_index.rst
  src/reference/acknowledgements.inc
  src/reference/sectionA_definitions.inc
  src/reference/sectionB_elements.inc
  src/reference/sectionC_interpretation.inc
  src/reference/sectionD_references.inc
  src/static/images/unofficial_version_dark_background.png
  src/static/images/unofficial_version_dark_background_green.png
  src/static/images/unofficial_version_dark_background_red.png
  src/static/templates/layout.html
Labels: normative
